if(typeof basic === "undefined") {
    basic.forever(function () {
        SW01.powerOn()
        basic.showNumber(SW01.temperature(SW01.Temperature.Celcius))
        basic.showNumber(SW01.temperature(SW01.Temperature.Fahrenheit))
        basic.showNumber(SW01.humidity(SW01.Humidity.RelativeHumidity))
        basic.showNumber(SW01.pressure(SW01.Pressure.HectoPascal))
        basic.showNumber(SW01.pressure(SW01.Pressure.MilliBar))
        basic.showNumber(SW01.dewpoint(SW01.Temperature.Celcius))
        basic.showNumber(SW01.dewpoint(SW01.Temperature.Fahrenheit))
        basic.showNumber(SW01.densityAltitude(SW01.Length.Meter))
        basic.showNumber(SW01.densityAltitude(SW01.Length.Feet))
        basic.showNumber(SW01.pressureAltitude(SW01.Length.Meter))
        basic.showNumber(SW01.pressureAltitude(SW01.Length.Feet))
        basic.showNumber(SW01.cloudBase(SW01.Length.Meter))
        basic.showNumber(SW01.cloudBase(SW01.Length.Feet))
        SW01.powerOff()
        basic.pause(100)
    })
}
