basic.forever(function () {
    SW01.powerOn()
    basic.showNumber(SW01.temperature(BME280_T.T_C))
    basic.showNumber(SW01.temperature(BME280_T.T_F))
    basic.showNumber(SW01.humidity(BME280_H.rh))
    basic.showNumber(SW01.pressure(BME280_P.hPa))
    basic.showNumber(SW01.pressure(BME280_P.mbar))
    basic.showNumber(SW01.dewpoint(BME280_D.T_C))
    basic.showNumber(SW01.dewpoint(BME280_D.T_F))
    basic.showNumber(SW01.densityAltitude(LENGTH_U.METER))
    basic.showNumber(SW01.densityAltitude(LENGTH_U.FEET))
    basic.showNumber(SW01.pressureAltitude(LENGTH_U.METER))
    basic.showNumber(SW01.pressureAltitude(LENGTH_U.FEET))
    basic.showNumber(SW01.cloudBase(LENGTH_U.METER))
    basic.showNumber(SW01.cloudBase(LENGTH_U.FEET))
    SW01.powerOff()
    basic.pause(100)
})

