basic.forever(function () {
    SW01.powerOn()
    basic.showNumber(SW01.temperature(Temperature.Celcius))
    basic.showNumber(SW01.temperature(Temperature.Fahrenheit))
    basic.showNumber(SW01.humidity(Humidity.RelativeHumidity))
    basic.showNumber(SW01.pressure(Pressure.HectoPascal))
    basic.showNumber(SW01.pressure(Pressure.MilliBar))
    basic.showNumber(SW01.dewpoint(Temperature.Celcius))
    basic.showNumber(SW01.dewpoint(Temperature.Fahrenheit))
    basic.showNumber(SW01.densityAltitude(Length.Meter))
    basic.showNumber(SW01.densityAltitude(Length.Feet))
    basic.showNumber(SW01.pressureAltitude(Length.Meter))
    basic.showNumber(SW01.pressureAltitude(Length.Feet))
    basic.showNumber(SW01.cloudBase(Length.Meter))
    basic.showNumber(SW01.cloudBase(Length.Feet))
    SW01.powerOff()
    basic.pause(100)
})

